---
- hosts: all
  become: yes
  tasks:
    - name: Update and install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest application image from Docker Hub
      docker_image:
        name: myapp:latest
        source: pull

    - name: Run the application container
      docker_container:
        name: myapp
        image: myapp:latest
        state: started
        ports:
          - "80:80"

    - name: Download ngrok
      get_url:
        url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        dest: /tmp/ngrok.zip

    - name: Unzip ngrok
      unarchive:
        src: /tmp/ngrok.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Run ngrok
      command: nohup ./ngrok http 80 --authtoken {{ ngrok_authtoken }} &
      args:
        chdir: /usr/local/bin/
      async: 30
      poll: 0

    - name: Wait for ngrok to start
      wait_for:
        port: 4040
        delay: 10

    - name: Get ngrok public URL
      uri:
        url: http://127.0.0.1:4040/api/tunnels
        return_content: yes
      register: ngrok_tunnels

    - name: Show ngrok public URL
      debug:
        msg: "Ngrok public URL is {{ ngrok_tunnels.json.tunnels[0].public_url }}"
